// numstr.cpp -- following number input with line input

#include <iostream>

int main(int argc, char *argv[])
{
    using namespace std;

    cout << "What year was your hous built?\n";
    int year;
    cin >> year;
    // NOTE: you never get the opportunity to enter the address.
    // The problem is that when cin reads the year, it leaves the
    // newline generated by the Enter Key in the input queue.
    // Then cin.getline() reads the newline as an empty line and
    // assigns a null string to the address array.
    // cin.get(); // or cin.get(ch);
    // or (cin >> year).get()
    cout << "What is its street address?\n";
    char address[80];
    cin.getline(address, 80);
    cout << "Year built: " << year << endl;
    cout << "Address: " << address << endl;
    cout << "Done!\n";
    return 0;
}
